name: Build and Push Docker Image

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Connect to Tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:cicd
          use-cache: true

      - name: Log in to private registry
        run: echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login ${{ secrets.REGISTRY_URL }} -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.REGISTRY_URL }}/controlplane:latest \
                       -t ${{ secrets.REGISTRY_URL }}/controlplane:${{ github.sha }} \
                       .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.REGISTRY_URL }}/controlplane:latest
          docker push ${{ secrets.REGISTRY_URL }}/controlplane:${{ github.sha }}
